{% set name = "pytask-latex" %}
{% set version = "0.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask_latex-{{ version }}.tar.gz
  sha256: eb5720fd03f45e47553a7e0a33f424a7107f0dd670795af565ffac4d1078d737

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
    - toml
  run:
    - python >=3.6
    - pytask >=0.1.0
    - latex-dependency-scanner

test:
  imports:
    - pytask_latex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-latex
  summary: Compile LaTeX documents with pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-latex
  doc_url: https://github.com/pytask-dev/pytask-latex

extra:
  recipe-maintainers:
    - tobiasraabe
