{% set name = "pytask-latex" %}
{% set version = "0.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytask_latex-{{ version }}.tar.gz
  sha256: a92fd1267583b506cc1d5db9c16e64d54bb8d0de9d54dbdd48451fbca7e28a57

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
    - toml
  run:
    - latex-dependency-scanner >=0.1.1
    - pluggy >=1.0.0
    - python >={{ python_min }}
    - pytask >=0.4.0

test:
  imports:
    - pytask_latex
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pytask-dev/pytask-latex
  summary: Compile LaTeX documents with pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-latex
  doc_url: https://github.com/pytask-dev/pytask-latex

extra:
  recipe-maintainers:
    - tobiasraabe
