{% set name = "pytask-latex" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask_latex-{{ version }}.tar.gz
  sha256: 59ad9bb32c2e0a1714c865987624ce48705fd009c84153f551008ef6f676e55d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
    - toml
  run:
    - python >=3.7
    - pytask >=0.1.7
    - latex-dependency-scanner >=0.1.1

test:
  imports:
    - pytask_latex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-latex
  summary: Compile LaTeX documents with pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-latex
  doc_url: https://github.com/pytask-dev/pytask-latex

extra:
  recipe-maintainers:
    - tobiasraabe
