{% set name = "pytask-latex" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask_latex-{{ version }}.tar.gz
  sha256: aa0529ab6c087c755c1f8d71ed216ad29cc8fb06527bc273e06140cf90f21a83

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pytask >=0.0.11
    - latex-dependency-scanner

test:
  imports:
    - pytask_latex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-latex
  summary: Compile LaTeX documents with pytask.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-latex
  doc_url: https://github.com/pytask-dev/pytask-latex

extra:
  recipe-maintainers:
    - tobiasraabe
